use_frameworks!

target 'MGDeeplinkNavigator_Example' do
  pod 'MGDeeplinkNavigator/MGDeeplinkNavigator_Extension', :path => '../'

  target 'MGDeeplinkNavigator_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
  end
end
